import streamlit as st
import pandas as pd
import county_data
import chart
import database

st.set_page_config(page_title='Home Price Estimator', layout="centered")


# CSS to adjust the title position
st.markdown(
    """
    <style>
    .main > div:first-child {
        padding-top: 10px;  
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.title('Home Price Estimator')

st.text('An interactive map of single-family home listings in the Philly metro area')


st.sidebar.title('Select Price Range')

price_input = st.sidebar.slider(
    label='Price Range',
    min_value=0,
    max_value=3000000,
    step=10000,
    value=(0, 470000),
    format="$%d",
    label_visibility='hidden'
)

st.sidebar.title('Select Home Features')

sqft=st.sidebar.slider(label='Square Footage (sqft)', min_value=0, max_value=25000, step=100, value=(2000, 4300), format="%d")
bedrooms=st.sidebar.slider(label='Bedrooms', min_value=0, max_value=15, step=1, value=(2, 5), format="%d")
bathrooms=st.sidebar.slider(label='Bathrooms', min_value=0.0, max_value=15.5, step=0.5, value=(1.5, 5.0), format="%f")

listings_predict = database.get_listings(price_input, sqft, bedrooms, bathrooms)
price_groups = database.get_price_groups() # list of unique price groups

counties_df = county_data.get_county_data()
greater_philly = county_data.get_greater_philly_fips()

viz = chart.plot_viz(listings_predict, counties_df, greater_philly, price_groups)
st.altair_chart(viz)

st.markdown("""
**Note:**  
This tool provides price estimates generated by a machine learning model leveraging property sales records, satellite imagery, and local demographic data. For more information about the methodology, please visit my [GitHub page](https://github.com/Sharanjv/Data-Science-Projects/tree/main/Synthesizing%20Home%20Features%2C%20Demographics%2C%20and%20Satellite%20Imagery%20for%20Property%20Price%20Prediction). The listings are current as of December 2023.  

*Disclaimer: This application is for educational purposes only.*  
""")



